### ISSUE TITLE
Upcoming Events VBO not working

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/content.uiowa.edu#2]
This appears to be related to the `Search Events` exposed filter view. If you remove the view or place the `Upcoming Events VBO` view above the `Search Events` view then the VBO's work.

**Comment by adamdelaney** [comment]
I have disabled the search events exposed filter view on the dashboard per the client request.

**Comment by markahrens** [comment]
Reworked the dashboard page to resolve this issue
