### ISSUE TITLE
Request: Venue ID in Events listing API endpoint

### ISSUE THREAD

**Issue by quamsta** [ITS-UofIowa/content.uiowa.edu#4]
Currently we only get geo/location information from the events listing endpoint:

`        "room_number": "Lynch Snyder Green ",
        "location_name": "Hancher Auditorium",
        "venue_url": "https://hancher.uiowa.edu",
        "address": "141 Park Road, Iowa City, IA 52242",
        "geo": {
          "latitude": "41.670056800000",
          "longitude": "-91.537494800000",
          "street": "141 Park Road",
          "city": "Iowa City",
          "state": "IA",
          "country": "US",
          "zip": "52242"
        `
But it would be really helpful if we could get the venue ID as well. We have a few features in After Class that work a lot better when we have a unique identifier for the venue (our "Near Me" page, for example)

**Comment by markahrens** [comment]
This should be resolved by 
https://github.com/ITS-UofIowa/content.uiowa.edu/commit/c8b087d617d6ed02592afe50fd2253177911549a

There is a new value in the JSON called location_id which should be the unique identifier for the location, if there is one.
